# Generated by Django 3.2.5 on 2021-07-09 16:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('talented_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Talents',
            new_name='Talent',
        ),
    ]
