# Generated by Django 3.2.5 on 2021-07-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talented_app', '0002_rename_talents_talent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(max_length=255)),
                ('endurance', models.IntegerField(default=1)),
                ('strength', models.IntegerField(default=1)),
                ('power', models.IntegerField(default=1)),
                ('speed', models.IntegerField(default=1)),
                ('agility', models.IntegerField(default=1)),
                ('flexibility', models.IntegerField(default=1)),
                ('nerve', models.IntegerField(default=1)),
                ('durability', models.IntegerField(default=1)),
                ('handeye_coordination', models.IntegerField(default=1)),
                ('analytic_aptitude', models.IntegerField(default=1)),
                ('total', models.IntegerField(null=True)),
            ],
        ),
    ]
