# Generated by Django 3.2.5 on 2021-07-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talented_app', '0005_auto_20210712_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='talent',
            name='attribute_agility',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='talent',
            name='attribute_analytic_aptitude',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='talent',
            name='attribute_durability',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='talent',
            name='attribute_endurance',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='talent',
            name='attribute_flexibility',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='talent',
            name='attribute_handeye_coordination',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='talent',
            name='attribute_nerve',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='talent',
            name='attribute_power',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='talent',
            name='attribute_speed',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='talent',
            name='attribute_strength',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
